#pragma once

#include <stdint.h>

namespace agi {
namespace msp {

static constexpr int MIN_LENGTH = 6;
static constexpr int MAX_PAYLOAD = 16;

// direction of the message
enum DIRECTION : uint16_t { SEND = '<', RECV = '>' };

// uncommented if implemented and tested
enum CODE : uint16_t {
  // API_VERSION                    = 1,
  // FC_VARIANT                     = 2,
  // FC_VERSION                     = 3,
  // BOARD_INFO                     = 4,
  // BUILD_INFO                     = 5,
  // INAV_PID                       = 6,
  // SET_INAV_PID                   = 7,
  // NAME                           = 10,  // out message
  // SET_NAME                       = 11,  // in message
  // NAV_POSHOLD                    = 12,  // only in iNav
  // SET_NAV_POSHOLD                = 13,  // only in iNav
  // CALIBRATION_DATA               = 14,
  // SET_CALIBRATION_DATA           = 15,
  // POSITION_ESTIMATION_CONFIG     = 16,
  // SET_POSITION_ESTIMATION_CONFIG = 17,
  // WP_MISSION_LOAD                = 18,  // Load mission from NVRAM
  // WP_MISSION_SAVE                = 19,  // Save mission to NVRAM
  // WP_GETINFO                     = 20,
  // RTH_AND_LAND_CONFIG            = 21,
  // SET_RTH_AND_LAND_CONFIG        = 22,
  // FW_CONFIG                      = 23,
  // SET_FW_CONFIG                  = 24,
  // BATTERY_CONFIG                 = 32,  // not avaialable in iNav
  // SET_BATTERY_CONFIG             = 33,  // not avaialable in iNav
  // MODE_RANGES                    = 34,
  // SET_MODE_RANGE                 = 35,
  // FEATURE                        = 36,
  // SET_FEATURE                    = 37,
  // BOARD_ALIGNMENT                = 38,
  // SET_BOARD_ALIGNMENT            = 39,
  // CURRENT_METER_CONFIG           = 40,
  // SET_CURRENT_METER_CONFIG       = 41,
  // MIXER                          = 42,
  // SET_MIXER                      = 43,
  // RX_CONFIG                      = 44,
  // SET_RX_CONFIG                  = 45,
  // LED_COLORS                     = 46,
  // SET_LED_COLORS                 = 47,
  // LED_STRIP_CONFIG               = 48,
  // SET_LED_STRIP_CONFIG           = 49,
  // RSSI_CONFIG                    = 50,
  // SET_RSSI_CONFIG                = 51,
  // ADJUSTMENT_RANGES              = 52,
  // SET_ADJUSTMENT_RANGE           = 53,
  // CF_SERIAL_CONFIG               = 54,
  // SET_CF_SERIAL_CONFIG           = 55,
  // VOLTAGE_METER_CONFIG           = 56,
  // SET_VOLTAGE_METER_CONFIG       = 57,
  // SONAR_ALTITUDE                 = 58,
  // PID_CONTROLLER                 = 59,
  // SET_PID_CONTROLLER             = 60,
  // ARMING_CONFIG                  = 61,
  // SET_ARMING_CONFIG              = 62,
  // RX_MAP                         = 64,
  // SET_RX_MAP                     = 65,
  // BF_CONFIG                      = 66,  // depricated, out message
  // SET_BF_CONFIG                  = 67,  // depricated, in message
  // REBOOT                         = 68,
  // BF_BUILD_INFO                  = 69,  // depricated, iNav
  // DATAFLASH_SUMMARY              = 70,
  // DATAFLASH_READ                 = 71,
  // DATAFLASH_ERASE                = 72,
  // LOOP_TIME                      = 73,  // depricated, iNav
  // SET_LOOP_TIME                  = 74,  // depricated, iNav
  // FAILSAFE_CONFIG                = 75,
  // SET_FAILSAFE_CONFIG            = 76,
  // RXFAIL_CONFIG                  = 77,  // depricated, iNav
  // SET_RXFAIL_CONFIG              = 78,  // depricated, iNav
  // SDCARD_SUMMARY                 = 79,
  // BLACKBOX_CONFIG                = 80,
  // SET_BLACKBOX_CONFIG            = 81,
  // TRANSPONDER_CONFIG             = 82,
  // SET_TRANSPONDER_CONFIG         = 83,
  // OSD_CONFIG                     = 84,  // out message, betaflight
  // SET_OSD_CONFIG                 = 85,  // in message, betaflight
  // OSD_CHAR_READ                  = 86,  // out message, betaflight
  // OSD_CHAR_WRITE                 = 87,
  // VTX_CONFIG                     = 88,
  // SET_VTX_CONFIG                 = 89,
  // ADVANCED_CONFIG                = 90,
  // SET_ADVANCED_CONFIG            = 91,
  // FILTER_CONFIG                  = 92,
  // SET_FILTER_CONFIG              = 93,
  // PID_ADVANCED                   = 94,
  // SET_PID_ADVANCED               = 95,
  // SENSOR_CONFIG                  = 96,
  // SET_SENSOR_CONFIG              = 97,
  // CAMERA_CONTROL                 = 98,   // SPECIAL_PARAMETERS
  // SET_ARMING_DISABLED            = 99,   // SET_SPECIAL_PARAMETERS
  // IDENT                          = 100,  // depricated
  // STATUS                         = 101,
  // RAW_IMU                        = 102,
  // SERVO                          = 103,
  // MOTOR                          = 104,
  // RC                             = 105,
  // RAW_GPS                        = 106,
  // COMP_GPS                       = 107,
  // ATTITUDE                       = 108,
  // ALTITUDE                       = 109,
  ANALOG = 110,
  // RC_TUNING                      = 111,
  // PID                            = 112,
  // ACTIVEBOXES                    = 113,  // depricated, iNav
  // MISC                           = 114,  // depricated, iNav
  // MOTOR_PINS                     = 115,  // depricated, iNav
  // BOXNAMES                       = 116,
  // PIDNAMES                       = 117,
  // WP                             = 118,
  // BOXIDS                         = 119,
  // SERVO_CONF                     = 120,
  // NAV_STATUS                     = 121,
  // NAV_CONFIG                     = 122,
  // MOTOR_3D_CONFIG                = 124,
  // RC_DEADBAND                    = 125,
  // SENSOR_ALIGNMENT               = 126,
  // LED_STRIP_MODECOLOR            = 127,
  // VOLTAGE_METERS                 = 128,  // not present in iNav
  // CURRENT_METERS                 = 129,  // not present in iNav
  // BATTERY_STATE                  = 130,  // not present in iNav
  // MOTOR_CONFIG                   = 131,  // out message
  // GPS_CONFIG                     = 132,  // out message
  // COMPASS_CONFIG                 = 133,  // out message
  // ESC_SENSOR_DATA                = 134,  // out message
  // STATUS_EX                      = 150,
  // SENSOR_STATUS                  = 151,  // only iNav
  // UID                            = 160,
  // GPSSVINFO                      = 164,
  // GPSSTATISTICS                  = 166,
  // OSD_VIDEO_CONFIG               = 180,
  // SET_OSD_VIDEO_CONFIG           = 181,
  // DISPLAYPORT                    = 182,
  // COPY_PROFILE                   = 183,  // not in iNav
  // BEEPER_CONFIG                  = 184,  // not in iNav
  // SET_BEEPER_CONFIG              = 185,  // not in iNav
  // SET_TX_INFO                    = 186,  // in message
  // TX_INFO                        = 187,  // out message
  SET_RAW_RC = 200,
  // SET_RAW_GPS                    = 201,
  // SET_PID                        = 202,
  // SET_BOX                        = 203,  // depricated
  // SET_RC_TUNING                  = 204,
  // ACC_CALIBRATION                = 205,
  // MAG_CALIBRATION                = 206,
  // SET_MISC                       = 207,  // depricated
  // RESET_CONF                     = 208,
  // SET_WP                         = 209,
  // SELECT_SETTING                 = 210,
  // SET_HEADING                    = 211,
  // SET_SERVO_CONF                 = 212,
  SET_MOTOR = 214,
  // SET_NAV_CONFIG                 = 215,
  // SET_MOTOR_3D_CONF              = 217,
  // SET_RC_DEADBAND                = 218,
  // SET_RESET_CURR_PID             = 219,
  // SET_SENSOR_ALIGNMENT           = 220,
  // SET_LED_STRIP_MODECOLOR        = 221,
  // SET_MOTOR_CONFIG               = 222,  // out message
  // SET_GPS_CONFIG                 = 223,  // out message
  // SET_COMPASS_CONFIG             = 224,  // out message
  // SET_ACC_TRIM                   = 239,  // in message
  // ACC_TRIM                       = 240,  // out message
  // SERVO_MIX_RULES                = 241,  // out message
  // SET_SERVO_MIX_RULE             = 242,  // in message
  // PASSTHROUGH_SERIAL             = 244,  // not used in CF, BF, iNav
  // SET_4WAY_IF                    = 245,  // in message
  // SET_RTC                        = 246,  // in message
  // RTC                            = 247,  // out message
  // EEPROM_WRITE                   = 250,  // in message
  // RESERVE_1                      = 251,  // reserved for system usage
  // RESERVE_2                      = 252,  // reserved for system usage
  // DEBUGMSG                       = 253,  // out message
  // DEBUG                          = 254,  // out message
  // V2_FRAME                       = 255,  // MSPv2 over MSPv1

  // COMMON_TZ               = 0x1001,  // out message, TZ offset
  // COMMON_SET_TZ           = 0x1002,  // in message, sets the TZ offset
  // COMMON_SETTING          = 0x1003,  // in/out message, returns setting
  // COMMON_SET_SETTING      = 0x1004,  // in message, sets a setting value
  // COMMON_MOTOR_MIXER      = 0x1005,
  // COMMON_SET_MOTOR_MIXER  = 0x1006,
  // INAV_STATUS             = 0x2000,
  // INAV_OPTICAL_FLOW       = 0x2001,
  // INAV_ANALOG             = 0x2002,
  // INAV_MISC               = 0x2003,
  // INAV_SET_MISC           = 0x2004,
  // INAV_BATTERY_CONFIG     = 0x2005,
  // INAV_SET_BATTERY_CONFIG = 0x2006,
  // INAV_RATE_PROFILE       = 0x2007,
  // INAV_SET_RATE_PROFILE   = 0x2008,
  // INAV_AIR_SPEED          = 0x2009
};
}  // namespace msp


}  // namespace agi
